// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: api/capmesh/v1/capture.proto

package capmeshv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Connect_FullMethodName = "/capmesh.v1.AgentService/Connect"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentServiceClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, AgentCommand], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, AgentCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, AgentCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectClient = grpc.BidiStreamingClient[AgentMessage, AgentCommand]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
type AgentServiceServer interface {
	Connect(grpc.BidiStreamingServer[AgentMessage, AgentCommand]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Connect(grpc.BidiStreamingServer[AgentMessage, AgentCommand]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).Connect(&grpc.GenericServerStream[AgentMessage, AgentCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ConnectServer = grpc.BidiStreamingServer[AgentMessage, AgentCommand]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capmesh.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _AgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/capmesh/v1/capture.proto",
}

const (
	CaptureService_CreateSession_FullMethodName = "/capmesh.v1.CaptureService/CreateSession"
	CaptureService_StopSession_FullMethodName   = "/capmesh.v1.CaptureService/StopSession"
	CaptureService_GetSession_FullMethodName    = "/capmesh.v1.CaptureService/GetSession"
	CaptureService_StreamPackets_FullMethodName = "/capmesh.v1.CaptureService/StreamPackets"
)

// CaptureServiceClient is the client API for CaptureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CaptureServiceClient interface {
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CaptureSession, error)
	StopSession(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*CaptureSession, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*CaptureSession, error)
	StreamPackets(ctx context.Context, in *StreamPacketsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PacketBatch], error)
}

type captureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCaptureServiceClient(cc grpc.ClientConnInterface) CaptureServiceClient {
	return &captureServiceClient{cc}
}

func (c *captureServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CaptureSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureSession)
	err := c.cc.Invoke(ctx, CaptureService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureServiceClient) StopSession(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*CaptureSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureSession)
	err := c.cc.Invoke(ctx, CaptureService_StopSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*CaptureSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureSession)
	err := c.cc.Invoke(ctx, CaptureService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *captureServiceClient) StreamPackets(ctx context.Context, in *StreamPacketsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PacketBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CaptureService_ServiceDesc.Streams[0], CaptureService_StreamPackets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamPacketsRequest, PacketBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaptureService_StreamPacketsClient = grpc.ServerStreamingClient[PacketBatch]

// CaptureServiceServer is the server API for CaptureService service.
// All implementations must embed UnimplementedCaptureServiceServer
// for forward compatibility.
type CaptureServiceServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*CaptureSession, error)
	StopSession(context.Context, *StopSessionRequest) (*CaptureSession, error)
	GetSession(context.Context, *GetSessionRequest) (*CaptureSession, error)
	StreamPackets(*StreamPacketsRequest, grpc.ServerStreamingServer[PacketBatch]) error
	mustEmbedUnimplementedCaptureServiceServer()
}

// UnimplementedCaptureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaptureServiceServer struct{}

func (UnimplementedCaptureServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CaptureSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedCaptureServiceServer) StopSession(context.Context, *StopSessionRequest) (*CaptureSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSession not implemented")
}
func (UnimplementedCaptureServiceServer) GetSession(context.Context, *GetSessionRequest) (*CaptureSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedCaptureServiceServer) StreamPackets(*StreamPacketsRequest, grpc.ServerStreamingServer[PacketBatch]) error {
	return status.Errorf(codes.Unimplemented, "method StreamPackets not implemented")
}
func (UnimplementedCaptureServiceServer) mustEmbedUnimplementedCaptureServiceServer() {}
func (UnimplementedCaptureServiceServer) testEmbeddedByValue()                        {}

// UnsafeCaptureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaptureServiceServer will
// result in compilation errors.
type UnsafeCaptureServiceServer interface {
	mustEmbedUnimplementedCaptureServiceServer()
}

func RegisterCaptureServiceServer(s grpc.ServiceRegistrar, srv CaptureServiceServer) {
	// If the following call pancis, it indicates UnimplementedCaptureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaptureService_ServiceDesc, srv)
}

func _CaptureService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureService_StopSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureServiceServer).StopSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureService_StopSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureServiceServer).StopSession(ctx, req.(*StopSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaptureServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaptureService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaptureServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CaptureService_StreamPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamPacketsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CaptureServiceServer).StreamPackets(m, &grpc.GenericServerStream[StreamPacketsRequest, PacketBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CaptureService_StreamPacketsServer = grpc.ServerStreamingServer[PacketBatch]

// CaptureService_ServiceDesc is the grpc.ServiceDesc for CaptureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaptureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capmesh.v1.CaptureService",
	HandlerType: (*CaptureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _CaptureService_CreateSession_Handler,
		},
		{
			MethodName: "StopSession",
			Handler:    _CaptureService_StopSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _CaptureService_GetSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPackets",
			Handler:       _CaptureService_StreamPackets_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/capmesh/v1/capture.proto",
}
