// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.26.1
// source: api/capmesh/v1/capture.proto

package capmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Register      *RegisterAgent         `protobuf:"bytes,1,opt,name=register,proto3" json:"register,omitempty"`
	Heartbeat     *Heartbeat             `protobuf:"bytes,2,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Status        *CaptureStatus         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Batch         *PacketBatch           `protobuf:"bytes,4,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetRegister() *RegisterAgent {
	if x != nil {
		return x.Register
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

func (x *AgentMessage) GetStatus() *CaptureStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AgentMessage) GetBatch() *PacketBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type AgentCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *StartCapture          `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop          *StopCapture           `protobuf:"bytes,2,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{1}
}

func (x *AgentCommand) GetStart() *StartCapture {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *AgentCommand) GetStop() *StopCapture {
	if x != nil {
		return x.Stop
	}
	return nil
}

type RegisterAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Interfaces    map[string]string      `protobuf:"bytes,2,rep,name=interfaces,proto3" json:"interfaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgent) Reset() {
	*x = RegisterAgent{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgent) ProtoMessage() {}

func (x *RegisterAgent) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgent.ProtoReflect.Descriptor instead.
func (*RegisterAgent) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAgent) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegisterAgent) GetInterfaces() map[string]string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type CaptureStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	SourceId      string                 `protobuf:"bytes,5,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureStatus) Reset() {
	*x = CaptureStatus{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureStatus) ProtoMessage() {}

func (x *CaptureStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureStatus.ProtoReflect.Descriptor instead.
func (*CaptureStatus) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{4}
}

func (x *CaptureStatus) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CaptureStatus) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CaptureStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CaptureStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CaptureStatus) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type StartCapture struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LogicalInterface string                 `protobuf:"bytes,2,opt,name=logical_interface,json=logicalInterface,proto3" json:"logical_interface,omitempty"`
	Filter           string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Snaplen          uint32                 `protobuf:"varint,4,opt,name=snaplen,proto3" json:"snaplen,omitempty"`
	Source           *CaptureSource         `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartCapture) Reset() {
	*x = StartCapture{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCapture) ProtoMessage() {}

func (x *StartCapture) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCapture.ProtoReflect.Descriptor instead.
func (*StartCapture) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{5}
}

func (x *StartCapture) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartCapture) GetLogicalInterface() string {
	if x != nil {
		return x.LogicalInterface
	}
	return ""
}

func (x *StartCapture) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *StartCapture) GetSnaplen() uint32 {
	if x != nil {
		return x.Snaplen
	}
	return 0
}

func (x *StartCapture) GetSource() *CaptureSource {
	if x != nil {
		return x.Source
	}
	return nil
}

type StopCapture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SourceId      string                 `protobuf:"bytes,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCapture) Reset() {
	*x = StopCapture{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCapture) ProtoMessage() {}

func (x *StopCapture) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCapture.ProtoReflect.Descriptor instead.
func (*StopCapture) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{6}
}

func (x *StopCapture) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StopCapture) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type CaptureSource struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TargetId         string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType       string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	NodeName         string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	LogicalInterface string                 `protobuf:"bytes,5,opt,name=logical_interface,json=logicalInterface,proto3" json:"logical_interface,omitempty"`
	InterfaceName    string                 `protobuf:"bytes,6,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Namespace        string                 `protobuf:"bytes,7,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName          string                 `protobuf:"bytes,8,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodUid           string                 `protobuf:"bytes,9,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	PodIp            string                 `protobuf:"bytes,10,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CaptureSource) Reset() {
	*x = CaptureSource{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureSource) ProtoMessage() {}

func (x *CaptureSource) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureSource.ProtoReflect.Descriptor instead.
func (*CaptureSource) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{7}
}

func (x *CaptureSource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CaptureSource) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *CaptureSource) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *CaptureSource) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CaptureSource) GetLogicalInterface() string {
	if x != nil {
		return x.LogicalInterface
	}
	return ""
}

func (x *CaptureSource) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *CaptureSource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CaptureSource) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *CaptureSource) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *CaptureSource) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

type PacketBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	InterfaceName string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Packets       []*Packet              `protobuf:"bytes,4,rep,name=packets,proto3" json:"packets,omitempty"`
	Source        *CaptureSource         `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketBatch) Reset() {
	*x = PacketBatch{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketBatch) ProtoMessage() {}

func (x *PacketBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketBatch.ProtoReflect.Descriptor instead.
func (*PacketBatch) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{8}
}

func (x *PacketBatch) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PacketBatch) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PacketBatch) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *PacketBatch) GetPackets() []*Packet {
	if x != nil {
		return x.Packets
	}
	return nil
}

func (x *PacketBatch) GetSource() *CaptureSource {
	if x != nil {
		return x.Source
	}
	return nil
}

type Packet struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs    int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	CapturedLength uint32                 `protobuf:"varint,2,opt,name=captured_length,json=capturedLength,proto3" json:"captured_length,omitempty"`
	OriginalLength uint32                 `protobuf:"varint,3,opt,name=original_length,json=originalLength,proto3" json:"original_length,omitempty"`
	LinkType       uint32                 `protobuf:"varint,4,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,5,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Data           []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{9}
}

func (x *Packet) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Packet) GetCapturedLength() uint32 {
	if x != nil {
		return x.CapturedLength
	}
	return 0
}

func (x *Packet) GetOriginalLength() uint32 {
	if x != nil {
		return x.OriginalLength
	}
	return 0
}

func (x *Packet) GetLinkType() uint32 {
	if x != nil {
		return x.LinkType
	}
	return 0
}

func (x *Packet) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Nodes            []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	LogicalInterface string                 `protobuf:"bytes,2,opt,name=logical_interface,json=logicalInterface,proto3" json:"logical_interface,omitempty"`
	Filter           string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Snaplen          uint32                 `protobuf:"varint,4,opt,name=snaplen,proto3" json:"snaplen,omitempty"`
	TtlSeconds       uint32                 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	ReorderWindowMs  uint32                 `protobuf:"varint,6,opt,name=reorder_window_ms,json=reorderWindowMs,proto3" json:"reorder_window_ms,omitempty"`
	Targets          []*CaptureTarget       `protobuf:"bytes,7,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSessionRequest) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *CreateSessionRequest) GetLogicalInterface() string {
	if x != nil {
		return x.LogicalInterface
	}
	return ""
}

func (x *CreateSessionRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *CreateSessionRequest) GetSnaplen() uint32 {
	if x != nil {
		return x.Snaplen
	}
	return 0
}

func (x *CreateSessionRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *CreateSessionRequest) GetReorderWindowMs() uint32 {
	if x != nil {
		return x.ReorderWindowMs
	}
	return 0
}

func (x *CreateSessionRequest) GetTargets() []*CaptureTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type StartContinuousCaptureRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Targets         []*CaptureTarget       `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	Filter          string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Snaplen         uint32                 `protobuf:"varint,3,opt,name=snaplen,proto3" json:"snaplen,omitempty"`
	ReorderWindowMs uint32                 `protobuf:"varint,4,opt,name=reorder_window_ms,json=reorderWindowMs,proto3" json:"reorder_window_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartContinuousCaptureRequest) Reset() {
	*x = StartContinuousCaptureRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContinuousCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContinuousCaptureRequest) ProtoMessage() {}

func (x *StartContinuousCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContinuousCaptureRequest.ProtoReflect.Descriptor instead.
func (*StartContinuousCaptureRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{11}
}

func (x *StartContinuousCaptureRequest) GetTargets() []*CaptureTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *StartContinuousCaptureRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *StartContinuousCaptureRequest) GetSnaplen() uint32 {
	if x != nil {
		return x.Snaplen
	}
	return 0
}

func (x *StartContinuousCaptureRequest) GetReorderWindowMs() uint32 {
	if x != nil {
		return x.ReorderWindowMs
	}
	return 0
}

type StopContinuousCaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContinuousCaptureRequest) Reset() {
	*x = StopContinuousCaptureRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContinuousCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContinuousCaptureRequest) ProtoMessage() {}

func (x *StopContinuousCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContinuousCaptureRequest.ProtoReflect.Descriptor instead.
func (*StopContinuousCaptureRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{12}
}

type GetContinuousCaptureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContinuousCaptureRequest) Reset() {
	*x = GetContinuousCaptureRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContinuousCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContinuousCaptureRequest) ProtoMessage() {}

func (x *GetContinuousCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContinuousCaptureRequest.ProtoReflect.Descriptor instead.
func (*GetContinuousCaptureRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{13}
}

type ContinuousCapture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartedAtNs   int64                  `protobuf:"varint,3,opt,name=started_at_ns,json=startedAtNs,proto3" json:"started_at_ns,omitempty"`
	RetainedSize  uint64                 `protobuf:"varint,4,opt,name=retained_size,json=retainedSize,proto3" json:"retained_size,omitempty"`
	SegmentCount  uint32                 `protobuf:"varint,5,opt,name=segment_count,json=segmentCount,proto3" json:"segment_count,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinuousCapture) Reset() {
	*x = ContinuousCapture{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinuousCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinuousCapture) ProtoMessage() {}

func (x *ContinuousCapture) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinuousCapture.ProtoReflect.Descriptor instead.
func (*ContinuousCapture) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{14}
}

func (x *ContinuousCapture) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ContinuousCapture) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContinuousCapture) GetStartedAtNs() int64 {
	if x != nil {
		return x.StartedAtNs
	}
	return 0
}

func (x *ContinuousCapture) GetRetainedSize() uint64 {
	if x != nil {
		return x.RetainedSize
	}
	return 0
}

func (x *ContinuousCapture) GetSegmentCount() uint32 {
	if x != nil {
		return x.SegmentCount
	}
	return 0
}

func (x *ContinuousCapture) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{15}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{16}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Interfaces    map[string]string      `protobuf:"bytes,2,rep,name=interfaces,proto3" json:"interfaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ConnectedAtNs int64                  `protobuf:"varint,3,opt,name=connected_at_ns,json=connectedAtNs,proto3" json:"connected_at_ns,omitempty"`
	LastSeenAtNs  int64                  `protobuf:"varint,4,opt,name=last_seen_at_ns,json=lastSeenAtNs,proto3" json:"last_seen_at_ns,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{17}
}

func (x *AgentInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AgentInfo) GetInterfaces() map[string]string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *AgentInfo) GetConnectedAtNs() int64 {
	if x != nil {
		return x.ConnectedAtNs
	}
	return 0
}

func (x *AgentInfo) GetLastSeenAtNs() int64 {
	if x != nil {
		return x.LastSeenAtNs
	}
	return 0
}

func (x *AgentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{18}
}

func (x *ListSessionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListSessionsRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*CaptureSession      `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{19}
}

func (x *ListSessionsResponse) GetSessions() []*CaptureSession {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type CaptureTarget struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InterfaceTarget *InterfaceTarget       `protobuf:"bytes,2,opt,name=interface_target,json=interfaceTarget,proto3" json:"interface_target,omitempty"`
	WorkloadTarget  *WorkloadTarget        `protobuf:"bytes,3,opt,name=workload_target,json=workloadTarget,proto3" json:"workload_target,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CaptureTarget) Reset() {
	*x = CaptureTarget{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureTarget) ProtoMessage() {}

func (x *CaptureTarget) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureTarget.ProtoReflect.Descriptor instead.
func (*CaptureTarget) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{20}
}

func (x *CaptureTarget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CaptureTarget) GetInterfaceTarget() *InterfaceTarget {
	if x != nil {
		return x.InterfaceTarget
	}
	return nil
}

func (x *CaptureTarget) GetWorkloadTarget() *WorkloadTarget {
	if x != nil {
		return x.WorkloadTarget
	}
	return nil
}

type InterfaceTarget struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Nodes            []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	LogicalInterface string                 `protobuf:"bytes,2,opt,name=logical_interface,json=logicalInterface,proto3" json:"logical_interface,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InterfaceTarget) Reset() {
	*x = InterfaceTarget{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceTarget) ProtoMessage() {}

func (x *InterfaceTarget) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceTarget.ProtoReflect.Descriptor instead.
func (*InterfaceTarget) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{21}
}

func (x *InterfaceTarget) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *InterfaceTarget) GetLogicalInterface() string {
	if x != nil {
		return x.LogicalInterface
	}
	return ""
}

type WorkloadTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Direction     string                 `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Follow        bool                   `protobuf:"varint,5,opt,name=follow,proto3" json:"follow,omitempty"`
	MaxPods       uint32                 `protobuf:"varint,6,opt,name=max_pods,json=maxPods,proto3" json:"max_pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadTarget) Reset() {
	*x = WorkloadTarget{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadTarget) ProtoMessage() {}

func (x *WorkloadTarget) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadTarget.ProtoReflect.Descriptor instead.
func (*WorkloadTarget) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{22}
}

func (x *WorkloadTarget) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkloadTarget) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WorkloadTarget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadTarget) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *WorkloadTarget) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *WorkloadTarget) GetMaxPods() uint32 {
	if x != nil {
		return x.MaxPods
	}
	return 0
}

type StopSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionRequest) Reset() {
	*x = StopSessionRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionRequest) ProtoMessage() {}

func (x *StopSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionRequest.ProtoReflect.Descriptor instead.
func (*StopSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{23}
}

func (x *StopSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{24}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StreamPacketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPacketsRequest) Reset() {
	*x = StreamPacketsRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPacketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPacketsRequest) ProtoMessage() {}

func (x *StreamPacketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPacketsRequest.ProtoReflect.Descriptor instead.
func (*StreamPacketsRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{25}
}

func (x *StreamPacketsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CaptureSession struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nodes            []string               `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	LogicalInterface string                 `protobuf:"bytes,3,opt,name=logical_interface,json=logicalInterface,proto3" json:"logical_interface,omitempty"`
	Filter           string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Snaplen          uint32                 `protobuf:"varint,5,opt,name=snaplen,proto3" json:"snaplen,omitempty"`
	CreatedAtNs      int64                  `protobuf:"varint,6,opt,name=created_at_ns,json=createdAtNs,proto3" json:"created_at_ns,omitempty"`
	ExpiresAtNs      int64                  `protobuf:"varint,7,opt,name=expires_at_ns,json=expiresAtNs,proto3" json:"expires_at_ns,omitempty"`
	Status           string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Message          string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	Targets          []*CaptureTarget       `protobuf:"bytes,10,rep,name=targets,proto3" json:"targets,omitempty"`
	Mode             string                 `protobuf:"bytes,11,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CaptureSession) Reset() {
	*x = CaptureSession{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureSession) ProtoMessage() {}

func (x *CaptureSession) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureSession.ProtoReflect.Descriptor instead.
func (*CaptureSession) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{26}
}

func (x *CaptureSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CaptureSession) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *CaptureSession) GetLogicalInterface() string {
	if x != nil {
		return x.LogicalInterface
	}
	return ""
}

func (x *CaptureSession) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *CaptureSession) GetSnaplen() uint32 {
	if x != nil {
		return x.Snaplen
	}
	return 0
}

func (x *CaptureSession) GetCreatedAtNs() int64 {
	if x != nil {
		return x.CreatedAtNs
	}
	return 0
}

func (x *CaptureSession) GetExpiresAtNs() int64 {
	if x != nil {
		return x.ExpiresAtNs
	}
	return 0
}

func (x *CaptureSession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CaptureSession) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CaptureSession) GetTargets() []*CaptureTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *CaptureSession) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

var File_api_capmesh_v1_capture_proto protoreflect.FileDescriptor

const file_api_capmesh_v1_capture_proto_rawDesc = "" +
	"\n" +
	"\x1capi/capmesh/v1/capture.proto\x12\n" +
	"capmesh.v1\"\xdc\x01\n" +
	"\fAgentMessage\x125\n" +
	"\bregister\x18\x01 \x01(\v2\x19.capmesh.v1.RegisterAgentR\bregister\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x15.capmesh.v1.HeartbeatR\theartbeat\x121\n" +
	"\x06status\x18\x03 \x01(\v2\x19.capmesh.v1.CaptureStatusR\x06status\x12-\n" +
	"\x05batch\x18\x04 \x01(\v2\x17.capmesh.v1.PacketBatchR\x05batch\"k\n" +
	"\fAgentCommand\x12.\n" +
	"\x05start\x18\x01 \x01(\v2\x18.capmesh.v1.StartCaptureR\x05start\x12+\n" +
	"\x04stop\x18\x02 \x01(\v2\x17.capmesh.v1.StopCaptureR\x04stop\"\xb6\x01\n" +
	"\rRegisterAgent\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12I\n" +
	"\n" +
	"interfaces\x18\x02 \x03(\v2).capmesh.v1.RegisterAgent.InterfacesEntryR\n" +
	"interfaces\x1a=\n" +
	"\x0fInterfacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\"\x94\x01\n" +
	"\rCaptureStatus\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1b\n" +
	"\tsource_id\x18\x05 \x01(\tR\bsourceId\"\xbf\x01\n" +
	"\fStartCapture\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12+\n" +
	"\x11logical_interface\x18\x02 \x01(\tR\x10logicalInterface\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x18\n" +
	"\asnaplen\x18\x04 \x01(\rR\asnaplen\x121\n" +
	"\x06source\x18\x05 \x01(\v2\x19.capmesh.v1.CaptureSourceR\x06source\"I\n" +
	"\vStopCapture\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\"\xb7\x02\n" +
	"\rCaptureSource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12+\n" +
	"\x11logical_interface\x18\x05 \x01(\tR\x10logicalInterface\x12%\n" +
	"\x0einterface_name\x18\x06 \x01(\tR\rinterfaceName\x12\x1c\n" +
	"\tnamespace\x18\a \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\b \x01(\tR\apodName\x12\x17\n" +
	"\apod_uid\x18\t \x01(\tR\x06podUid\x12\x15\n" +
	"\x06pod_ip\x18\n" +
	" \x01(\tR\x05podIp\"\xd1\x01\n" +
	"\vPacketBatch\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\x12,\n" +
	"\apackets\x18\x04 \x03(\v2\x12.capmesh.v1.PacketR\apackets\x121\n" +
	"\x06source\x18\x05 \x01(\v2\x19.capmesh.v1.CaptureSourceR\x06source\"\xd7\x01\n" +
	"\x06Packet\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12'\n" +
	"\x0fcaptured_length\x18\x02 \x01(\rR\x0ecapturedLength\x12'\n" +
	"\x0foriginal_length\x18\x03 \x01(\rR\x0eoriginalLength\x12\x1b\n" +
	"\tlink_type\x18\x04 \x01(\rR\blinkType\x12'\n" +
	"\x0fsequence_number\x18\x05 \x01(\x04R\x0esequenceNumber\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"\x8d\x02\n" +
	"\x14CreateSessionRequest\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes\x12+\n" +
	"\x11logical_interface\x18\x02 \x01(\tR\x10logicalInterface\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x18\n" +
	"\asnaplen\x18\x04 \x01(\rR\asnaplen\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\rR\n" +
	"ttlSeconds\x12*\n" +
	"\x11reorder_window_ms\x18\x06 \x01(\rR\x0freorderWindowMs\x123\n" +
	"\atargets\x18\a \x03(\v2\x19.capmesh.v1.CaptureTargetR\atargets\"\xb2\x01\n" +
	"\x1dStartContinuousCaptureRequest\x123\n" +
	"\atargets\x18\x01 \x03(\v2\x19.capmesh.v1.CaptureTargetR\atargets\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\x12\x18\n" +
	"\asnaplen\x18\x03 \x01(\rR\asnaplen\x12*\n" +
	"\x11reorder_window_ms\x18\x04 \x01(\rR\x0freorderWindowMs\"\x1e\n" +
	"\x1cStopContinuousCaptureRequest\"\x1d\n" +
	"\x1bGetContinuousCaptureRequest\"\xd2\x01\n" +
	"\x11ContinuousCapture\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\"\n" +
	"\rstarted_at_ns\x18\x03 \x01(\x03R\vstartedAtNs\x12#\n" +
	"\rretained_size\x18\x04 \x01(\x04R\fretainedSize\x12#\n" +
	"\rsegment_count\x18\x05 \x01(\rR\fsegmentCount\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"\x13\n" +
	"\x11ListAgentsRequest\"C\n" +
	"\x12ListAgentsResponse\x12-\n" +
	"\x06agents\x18\x01 \x03(\v2\x15.capmesh.v1.AgentInfoR\x06agents\"\x95\x02\n" +
	"\tAgentInfo\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12E\n" +
	"\n" +
	"interfaces\x18\x02 \x03(\v2%.capmesh.v1.AgentInfo.InterfacesEntryR\n" +
	"interfaces\x12&\n" +
	"\x0fconnected_at_ns\x18\x03 \x01(\x03R\rconnectedAtNs\x12%\n" +
	"\x0flast_seen_at_ns\x18\x04 \x01(\x03R\flastSeenAtNs\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x1a=\n" +
	"\x0fInterfacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x13ListSessionsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"N\n" +
	"\x14ListSessionsResponse\x126\n" +
	"\bsessions\x18\x01 \x03(\v2\x1a.capmesh.v1.CaptureSessionR\bsessions\"\xac\x01\n" +
	"\rCaptureTarget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12F\n" +
	"\x10interface_target\x18\x02 \x01(\v2\x1b.capmesh.v1.InterfaceTargetR\x0finterfaceTarget\x12C\n" +
	"\x0fworkload_target\x18\x03 \x01(\v2\x1a.capmesh.v1.WorkloadTargetR\x0eworkloadTarget\"T\n" +
	"\x0fInterfaceTarget\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes\x12+\n" +
	"\x11logical_interface\x18\x02 \x01(\tR\x10logicalInterface\"\xa7\x01\n" +
	"\x0eWorkloadTarget\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tdirection\x18\x04 \x01(\tR\tdirection\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06follow\x12\x19\n" +
	"\bmax_pods\x18\x06 \x01(\rR\amaxPods\"3\n" +
	"\x12StopSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"5\n" +
	"\x14StreamPacketsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xd8\x02\n" +
	"\x0eCaptureSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05nodes\x18\x02 \x03(\tR\x05nodes\x12+\n" +
	"\x11logical_interface\x18\x03 \x01(\tR\x10logicalInterface\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\x12\x18\n" +
	"\asnaplen\x18\x05 \x01(\rR\asnaplen\x12\"\n" +
	"\rcreated_at_ns\x18\x06 \x01(\x03R\vcreatedAtNs\x12\"\n" +
	"\rexpires_at_ns\x18\a \x01(\x03R\vexpiresAtNs\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\x123\n" +
	"\atargets\x18\n" +
	" \x03(\v2\x19.capmesh.v1.CaptureTargetR\atargets\x12\x12\n" +
	"\x04mode\x18\v \x01(\tR\x04mode2Q\n" +
	"\fAgentService\x12A\n" +
	"\aConnect\x12\x18.capmesh.v1.AgentMessage\x1a\x18.capmesh.v1.AgentCommand(\x010\x012\x87\x06\n" +
	"\x0eCaptureService\x12M\n" +
	"\rCreateSession\x12 .capmesh.v1.CreateSessionRequest\x1a\x1a.capmesh.v1.CaptureSession\x12I\n" +
	"\vStopSession\x12\x1e.capmesh.v1.StopSessionRequest\x1a\x1a.capmesh.v1.CaptureSession\x12G\n" +
	"\n" +
	"GetSession\x12\x1d.capmesh.v1.GetSessionRequest\x1a\x1a.capmesh.v1.CaptureSession\x12L\n" +
	"\rStreamPackets\x12 .capmesh.v1.StreamPacketsRequest\x1a\x17.capmesh.v1.PacketBatch0\x01\x12b\n" +
	"\x16StartContinuousCapture\x12).capmesh.v1.StartContinuousCaptureRequest\x1a\x1d.capmesh.v1.ContinuousCapture\x12`\n" +
	"\x15StopContinuousCapture\x12(.capmesh.v1.StopContinuousCaptureRequest\x1a\x1d.capmesh.v1.ContinuousCapture\x12^\n" +
	"\x14GetContinuousCapture\x12'.capmesh.v1.GetContinuousCaptureRequest\x1a\x1d.capmesh.v1.ContinuousCapture\x12K\n" +
	"\n" +
	"ListAgents\x12\x1d.capmesh.v1.ListAgentsRequest\x1a\x1e.capmesh.v1.ListAgentsResponse\x12Q\n" +
	"\fListSessions\x12\x1f.capmesh.v1.ListSessionsRequest\x1a .capmesh.v1.ListSessionsResponseB8Z6github.com/quyenhl16/cap-mesh/api/capmesh/v1;capmeshv1b\x06proto3"

var (
	file_api_capmesh_v1_capture_proto_rawDescOnce sync.Once
	file_api_capmesh_v1_capture_proto_rawDescData []byte
)

func file_api_capmesh_v1_capture_proto_rawDescGZIP() []byte {
	file_api_capmesh_v1_capture_proto_rawDescOnce.Do(func() {
		file_api_capmesh_v1_capture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_capmesh_v1_capture_proto_rawDesc), len(file_api_capmesh_v1_capture_proto_rawDesc)))
	})
	return file_api_capmesh_v1_capture_proto_rawDescData
}

var file_api_capmesh_v1_capture_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_api_capmesh_v1_capture_proto_goTypes = []any{
	(*AgentMessage)(nil),                  // 0: capmesh.v1.AgentMessage
	(*AgentCommand)(nil),                  // 1: capmesh.v1.AgentCommand
	(*RegisterAgent)(nil),                 // 2: capmesh.v1.RegisterAgent
	(*Heartbeat)(nil),                     // 3: capmesh.v1.Heartbeat
	(*CaptureStatus)(nil),                 // 4: capmesh.v1.CaptureStatus
	(*StartCapture)(nil),                  // 5: capmesh.v1.StartCapture
	(*StopCapture)(nil),                   // 6: capmesh.v1.StopCapture
	(*CaptureSource)(nil),                 // 7: capmesh.v1.CaptureSource
	(*PacketBatch)(nil),                   // 8: capmesh.v1.PacketBatch
	(*Packet)(nil),                        // 9: capmesh.v1.Packet
	(*CreateSessionRequest)(nil),          // 10: capmesh.v1.CreateSessionRequest
	(*StartContinuousCaptureRequest)(nil), // 11: capmesh.v1.StartContinuousCaptureRequest
	(*StopContinuousCaptureRequest)(nil),  // 12: capmesh.v1.StopContinuousCaptureRequest
	(*GetContinuousCaptureRequest)(nil),   // 13: capmesh.v1.GetContinuousCaptureRequest
	(*ContinuousCapture)(nil),             // 14: capmesh.v1.ContinuousCapture
	(*ListAgentsRequest)(nil),             // 15: capmesh.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),            // 16: capmesh.v1.ListAgentsResponse
	(*AgentInfo)(nil),                     // 17: capmesh.v1.AgentInfo
	(*ListSessionsRequest)(nil),           // 18: capmesh.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),          // 19: capmesh.v1.ListSessionsResponse
	(*CaptureTarget)(nil),                 // 20: capmesh.v1.CaptureTarget
	(*InterfaceTarget)(nil),               // 21: capmesh.v1.InterfaceTarget
	(*WorkloadTarget)(nil),                // 22: capmesh.v1.WorkloadTarget
	(*StopSessionRequest)(nil),            // 23: capmesh.v1.StopSessionRequest
	(*GetSessionRequest)(nil),             // 24: capmesh.v1.GetSessionRequest
	(*StreamPacketsRequest)(nil),          // 25: capmesh.v1.StreamPacketsRequest
	(*CaptureSession)(nil),                // 26: capmesh.v1.CaptureSession
	nil,                                   // 27: capmesh.v1.RegisterAgent.InterfacesEntry
	nil,                                   // 28: capmesh.v1.AgentInfo.InterfacesEntry
}
var file_api_capmesh_v1_capture_proto_depIdxs = []int32{
	2,  // 0: capmesh.v1.AgentMessage.register:type_name -> capmesh.v1.RegisterAgent
	3,  // 1: capmesh.v1.AgentMessage.heartbeat:type_name -> capmesh.v1.Heartbeat
	4,  // 2: capmesh.v1.AgentMessage.status:type_name -> capmesh.v1.CaptureStatus
	8,  // 3: capmesh.v1.AgentMessage.batch:type_name -> capmesh.v1.PacketBatch
	5,  // 4: capmesh.v1.AgentCommand.start:type_name -> capmesh.v1.StartCapture
	6,  // 5: capmesh.v1.AgentCommand.stop:type_name -> capmesh.v1.StopCapture
	27, // 6: capmesh.v1.RegisterAgent.interfaces:type_name -> capmesh.v1.RegisterAgent.InterfacesEntry
	7,  // 7: capmesh.v1.StartCapture.source:type_name -> capmesh.v1.CaptureSource
	9,  // 8: capmesh.v1.PacketBatch.packets:type_name -> capmesh.v1.Packet
	7,  // 9: capmesh.v1.PacketBatch.source:type_name -> capmesh.v1.CaptureSource
	20, // 10: capmesh.v1.CreateSessionRequest.targets:type_name -> capmesh.v1.CaptureTarget
	20, // 11: capmesh.v1.StartContinuousCaptureRequest.targets:type_name -> capmesh.v1.CaptureTarget
	17, // 12: capmesh.v1.ListAgentsResponse.agents:type_name -> capmesh.v1.AgentInfo
	28, // 13: capmesh.v1.AgentInfo.interfaces:type_name -> capmesh.v1.AgentInfo.InterfacesEntry
	26, // 14: capmesh.v1.ListSessionsResponse.sessions:type_name -> capmesh.v1.CaptureSession
	21, // 15: capmesh.v1.CaptureTarget.interface_target:type_name -> capmesh.v1.InterfaceTarget
	22, // 16: capmesh.v1.CaptureTarget.workload_target:type_name -> capmesh.v1.WorkloadTarget
	20, // 17: capmesh.v1.CaptureSession.targets:type_name -> capmesh.v1.CaptureTarget
	0,  // 18: capmesh.v1.AgentService.Connect:input_type -> capmesh.v1.AgentMessage
	10, // 19: capmesh.v1.CaptureService.CreateSession:input_type -> capmesh.v1.CreateSessionRequest
	23, // 20: capmesh.v1.CaptureService.StopSession:input_type -> capmesh.v1.StopSessionRequest
	24, // 21: capmesh.v1.CaptureService.GetSession:input_type -> capmesh.v1.GetSessionRequest
	25, // 22: capmesh.v1.CaptureService.StreamPackets:input_type -> capmesh.v1.StreamPacketsRequest
	11, // 23: capmesh.v1.CaptureService.StartContinuousCapture:input_type -> capmesh.v1.StartContinuousCaptureRequest
	12, // 24: capmesh.v1.CaptureService.StopContinuousCapture:input_type -> capmesh.v1.StopContinuousCaptureRequest
	13, // 25: capmesh.v1.CaptureService.GetContinuousCapture:input_type -> capmesh.v1.GetContinuousCaptureRequest
	15, // 26: capmesh.v1.CaptureService.ListAgents:input_type -> capmesh.v1.ListAgentsRequest
	18, // 27: capmesh.v1.CaptureService.ListSessions:input_type -> capmesh.v1.ListSessionsRequest
	1,  // 28: capmesh.v1.AgentService.Connect:output_type -> capmesh.v1.AgentCommand
	26, // 29: capmesh.v1.CaptureService.CreateSession:output_type -> capmesh.v1.CaptureSession
	26, // 30: capmesh.v1.CaptureService.StopSession:output_type -> capmesh.v1.CaptureSession
	26, // 31: capmesh.v1.CaptureService.GetSession:output_type -> capmesh.v1.CaptureSession
	8,  // 32: capmesh.v1.CaptureService.StreamPackets:output_type -> capmesh.v1.PacketBatch
	14, // 33: capmesh.v1.CaptureService.StartContinuousCapture:output_type -> capmesh.v1.ContinuousCapture
	14, // 34: capmesh.v1.CaptureService.StopContinuousCapture:output_type -> capmesh.v1.ContinuousCapture
	14, // 35: capmesh.v1.CaptureService.GetContinuousCapture:output_type -> capmesh.v1.ContinuousCapture
	16, // 36: capmesh.v1.CaptureService.ListAgents:output_type -> capmesh.v1.ListAgentsResponse
	19, // 37: capmesh.v1.CaptureService.ListSessions:output_type -> capmesh.v1.ListSessionsResponse
	28, // [28:38] is the sub-list for method output_type
	18, // [18:28] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_capmesh_v1_capture_proto_init() }
func file_api_capmesh_v1_capture_proto_init() {
	if File_api_capmesh_v1_capture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_capmesh_v1_capture_proto_rawDesc), len(file_api_capmesh_v1_capture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_capmesh_v1_capture_proto_goTypes,
		DependencyIndexes: file_api_capmesh_v1_capture_proto_depIdxs,
		MessageInfos:      file_api_capmesh_v1_capture_proto_msgTypes,
	}.Build()
	File_api_capmesh_v1_capture_proto = out.File
	file_api_capmesh_v1_capture_proto_goTypes = nil
	file_api_capmesh_v1_capture_proto_depIdxs = nil
}
