// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.26.1
// source: api/capmesh/v1/capture.proto

package capmeshv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Register      *RegisterAgent         `protobuf:"bytes,1,opt,name=register,proto3" json:"register,omitempty"`
	Heartbeat     *Heartbeat             `protobuf:"bytes,2,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	Status        *CaptureStatus         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Batch         *PacketBatch           `protobuf:"bytes,4,opt,name=batch,proto3" json:"batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetRegister() *RegisterAgent {
	if x != nil {
		return x.Register
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

func (x *AgentMessage) GetStatus() *CaptureStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *AgentMessage) GetBatch() *PacketBatch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type AgentCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *StartCapture          `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	Stop          *StopCapture           `protobuf:"bytes,2,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{1}
}

func (x *AgentCommand) GetStart() *StartCapture {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *AgentCommand) GetStop() *StopCapture {
	if x != nil {
		return x.Stop
	}
	return nil
}

type RegisterAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Interfaces    map[string]string      `protobuf:"bytes,2,rep,name=interfaces,proto3" json:"interfaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgent) Reset() {
	*x = RegisterAgent{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgent) ProtoMessage() {}

func (x *RegisterAgent) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgent.ProtoReflect.Descriptor instead.
func (*RegisterAgent) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAgent) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegisterAgent) GetInterfaces() map[string]string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs   int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{3}
}

func (x *Heartbeat) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

type CaptureStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureStatus) Reset() {
	*x = CaptureStatus{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureStatus) ProtoMessage() {}

func (x *CaptureStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureStatus.ProtoReflect.Descriptor instead.
func (*CaptureStatus) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{4}
}

func (x *CaptureStatus) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CaptureStatus) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *CaptureStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CaptureStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartCapture struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LogicalInterface string                 `protobuf:"bytes,2,opt,name=logical_interface,json=logicalInterface,proto3" json:"logical_interface,omitempty"`
	Filter           string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Snaplen          uint32                 `protobuf:"varint,4,opt,name=snaplen,proto3" json:"snaplen,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartCapture) Reset() {
	*x = StartCapture{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCapture) ProtoMessage() {}

func (x *StartCapture) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCapture.ProtoReflect.Descriptor instead.
func (*StartCapture) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{5}
}

func (x *StartCapture) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartCapture) GetLogicalInterface() string {
	if x != nil {
		return x.LogicalInterface
	}
	return ""
}

func (x *StartCapture) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *StartCapture) GetSnaplen() uint32 {
	if x != nil {
		return x.Snaplen
	}
	return 0
}

type StopCapture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopCapture) Reset() {
	*x = StopCapture{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopCapture) ProtoMessage() {}

func (x *StopCapture) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopCapture.ProtoReflect.Descriptor instead.
func (*StopCapture) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{6}
}

func (x *StopCapture) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PacketBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	InterfaceName string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	Packets       []*Packet              `protobuf:"bytes,4,rep,name=packets,proto3" json:"packets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketBatch) Reset() {
	*x = PacketBatch{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketBatch) ProtoMessage() {}

func (x *PacketBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketBatch.ProtoReflect.Descriptor instead.
func (*PacketBatch) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{7}
}

func (x *PacketBatch) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PacketBatch) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *PacketBatch) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *PacketBatch) GetPackets() []*Packet {
	if x != nil {
		return x.Packets
	}
	return nil
}

type Packet struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimestampNs    int64                  `protobuf:"varint,1,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	CapturedLength uint32                 `protobuf:"varint,2,opt,name=captured_length,json=capturedLength,proto3" json:"captured_length,omitempty"`
	OriginalLength uint32                 `protobuf:"varint,3,opt,name=original_length,json=originalLength,proto3" json:"original_length,omitempty"`
	LinkType       uint32                 `protobuf:"varint,4,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,5,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Data           []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{8}
}

func (x *Packet) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Packet) GetCapturedLength() uint32 {
	if x != nil {
		return x.CapturedLength
	}
	return 0
}

func (x *Packet) GetOriginalLength() uint32 {
	if x != nil {
		return x.OriginalLength
	}
	return 0
}

func (x *Packet) GetLinkType() uint32 {
	if x != nil {
		return x.LinkType
	}
	return 0
}

func (x *Packet) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateSessionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Nodes            []string               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	LogicalInterface string                 `protobuf:"bytes,2,opt,name=logical_interface,json=logicalInterface,proto3" json:"logical_interface,omitempty"`
	Filter           string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Snaplen          uint32                 `protobuf:"varint,4,opt,name=snaplen,proto3" json:"snaplen,omitempty"`
	TtlSeconds       uint32                 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	ReorderWindowMs  uint32                 `protobuf:"varint,6,opt,name=reorder_window_ms,json=reorderWindowMs,proto3" json:"reorder_window_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSessionRequest) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *CreateSessionRequest) GetLogicalInterface() string {
	if x != nil {
		return x.LogicalInterface
	}
	return ""
}

func (x *CreateSessionRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *CreateSessionRequest) GetSnaplen() uint32 {
	if x != nil {
		return x.Snaplen
	}
	return 0
}

func (x *CreateSessionRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *CreateSessionRequest) GetReorderWindowMs() uint32 {
	if x != nil {
		return x.ReorderWindowMs
	}
	return 0
}

type StopSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionRequest) Reset() {
	*x = StopSessionRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionRequest) ProtoMessage() {}

func (x *StopSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionRequest.ProtoReflect.Descriptor instead.
func (*StopSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{10}
}

func (x *StopSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{11}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StreamPacketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamPacketsRequest) Reset() {
	*x = StreamPacketsRequest{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamPacketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamPacketsRequest) ProtoMessage() {}

func (x *StreamPacketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamPacketsRequest.ProtoReflect.Descriptor instead.
func (*StreamPacketsRequest) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{12}
}

func (x *StreamPacketsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CaptureSession struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nodes            []string               `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	LogicalInterface string                 `protobuf:"bytes,3,opt,name=logical_interface,json=logicalInterface,proto3" json:"logical_interface,omitempty"`
	Filter           string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Snaplen          uint32                 `protobuf:"varint,5,opt,name=snaplen,proto3" json:"snaplen,omitempty"`
	CreatedAtNs      int64                  `protobuf:"varint,6,opt,name=created_at_ns,json=createdAtNs,proto3" json:"created_at_ns,omitempty"`
	ExpiresAtNs      int64                  `protobuf:"varint,7,opt,name=expires_at_ns,json=expiresAtNs,proto3" json:"expires_at_ns,omitempty"`
	Status           string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Message          string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CaptureSession) Reset() {
	*x = CaptureSession{}
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureSession) ProtoMessage() {}

func (x *CaptureSession) ProtoReflect() protoreflect.Message {
	mi := &file_api_capmesh_v1_capture_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureSession.ProtoReflect.Descriptor instead.
func (*CaptureSession) Descriptor() ([]byte, []int) {
	return file_api_capmesh_v1_capture_proto_rawDescGZIP(), []int{13}
}

func (x *CaptureSession) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CaptureSession) GetNodes() []string {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *CaptureSession) GetLogicalInterface() string {
	if x != nil {
		return x.LogicalInterface
	}
	return ""
}

func (x *CaptureSession) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *CaptureSession) GetSnaplen() uint32 {
	if x != nil {
		return x.Snaplen
	}
	return 0
}

func (x *CaptureSession) GetCreatedAtNs() int64 {
	if x != nil {
		return x.CreatedAtNs
	}
	return 0
}

func (x *CaptureSession) GetExpiresAtNs() int64 {
	if x != nil {
		return x.ExpiresAtNs
	}
	return 0
}

func (x *CaptureSession) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CaptureSession) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_capmesh_v1_capture_proto protoreflect.FileDescriptor

const file_api_capmesh_v1_capture_proto_rawDesc = "" +
	"\n" +
	"\x1capi/capmesh/v1/capture.proto\x12\n" +
	"capmesh.v1\"\xdc\x01\n" +
	"\fAgentMessage\x125\n" +
	"\bregister\x18\x01 \x01(\v2\x19.capmesh.v1.RegisterAgentR\bregister\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x15.capmesh.v1.HeartbeatR\theartbeat\x121\n" +
	"\x06status\x18\x03 \x01(\v2\x19.capmesh.v1.CaptureStatusR\x06status\x12-\n" +
	"\x05batch\x18\x04 \x01(\v2\x17.capmesh.v1.PacketBatchR\x05batch\"k\n" +
	"\fAgentCommand\x12.\n" +
	"\x05start\x18\x01 \x01(\v2\x18.capmesh.v1.StartCaptureR\x05start\x12+\n" +
	"\x04stop\x18\x02 \x01(\v2\x17.capmesh.v1.StopCaptureR\x04stop\"\xb6\x01\n" +
	"\rRegisterAgent\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12I\n" +
	"\n" +
	"interfaces\x18\x02 \x03(\v2).capmesh.v1.RegisterAgent.InterfacesEntryR\n" +
	"interfaces\x1a=\n" +
	"\x0fInterfacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\"w\n" +
	"\rCaptureStatus\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x8c\x01\n" +
	"\fStartCapture\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12+\n" +
	"\x11logical_interface\x18\x02 \x01(\tR\x10logicalInterface\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x18\n" +
	"\asnaplen\x18\x04 \x01(\rR\asnaplen\",\n" +
	"\vStopCapture\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x9e\x01\n" +
	"\vPacketBatch\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\x12,\n" +
	"\apackets\x18\x04 \x03(\v2\x12.capmesh.v1.PacketR\apackets\"\xd7\x01\n" +
	"\x06Packet\x12!\n" +
	"\ftimestamp_ns\x18\x01 \x01(\x03R\vtimestampNs\x12'\n" +
	"\x0fcaptured_length\x18\x02 \x01(\rR\x0ecapturedLength\x12'\n" +
	"\x0foriginal_length\x18\x03 \x01(\rR\x0eoriginalLength\x12\x1b\n" +
	"\tlink_type\x18\x04 \x01(\rR\blinkType\x12'\n" +
	"\x0fsequence_number\x18\x05 \x01(\x04R\x0esequenceNumber\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"\xd8\x01\n" +
	"\x14CreateSessionRequest\x12\x14\n" +
	"\x05nodes\x18\x01 \x03(\tR\x05nodes\x12+\n" +
	"\x11logical_interface\x18\x02 \x01(\tR\x10logicalInterface\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x18\n" +
	"\asnaplen\x18\x04 \x01(\rR\asnaplen\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\rR\n" +
	"ttlSeconds\x12*\n" +
	"\x11reorder_window_ms\x18\x06 \x01(\rR\x0freorderWindowMs\"3\n" +
	"\x12StopSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"5\n" +
	"\x14StreamPacketsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x8f\x02\n" +
	"\x0eCaptureSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05nodes\x18\x02 \x03(\tR\x05nodes\x12+\n" +
	"\x11logical_interface\x18\x03 \x01(\tR\x10logicalInterface\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\x12\x18\n" +
	"\asnaplen\x18\x05 \x01(\rR\asnaplen\x12\"\n" +
	"\rcreated_at_ns\x18\x06 \x01(\x03R\vcreatedAtNs\x12\"\n" +
	"\rexpires_at_ns\x18\a \x01(\x03R\vexpiresAtNs\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage2Q\n" +
	"\fAgentService\x12A\n" +
	"\aConnect\x12\x18.capmesh.v1.AgentMessage\x1a\x18.capmesh.v1.AgentCommand(\x010\x012\xc1\x02\n" +
	"\x0eCaptureService\x12M\n" +
	"\rCreateSession\x12 .capmesh.v1.CreateSessionRequest\x1a\x1a.capmesh.v1.CaptureSession\x12I\n" +
	"\vStopSession\x12\x1e.capmesh.v1.StopSessionRequest\x1a\x1a.capmesh.v1.CaptureSession\x12G\n" +
	"\n" +
	"GetSession\x12\x1d.capmesh.v1.GetSessionRequest\x1a\x1a.capmesh.v1.CaptureSession\x12L\n" +
	"\rStreamPackets\x12 .capmesh.v1.StreamPacketsRequest\x1a\x17.capmesh.v1.PacketBatch0\x01B8Z6github.com/quyenhl16/cap-mesh/api/capmesh/v1;capmeshv1b\x06proto3"

var (
	file_api_capmesh_v1_capture_proto_rawDescOnce sync.Once
	file_api_capmesh_v1_capture_proto_rawDescData []byte
)

func file_api_capmesh_v1_capture_proto_rawDescGZIP() []byte {
	file_api_capmesh_v1_capture_proto_rawDescOnce.Do(func() {
		file_api_capmesh_v1_capture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_capmesh_v1_capture_proto_rawDesc), len(file_api_capmesh_v1_capture_proto_rawDesc)))
	})
	return file_api_capmesh_v1_capture_proto_rawDescData
}

var file_api_capmesh_v1_capture_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_capmesh_v1_capture_proto_goTypes = []any{
	(*AgentMessage)(nil),         // 0: capmesh.v1.AgentMessage
	(*AgentCommand)(nil),         // 1: capmesh.v1.AgentCommand
	(*RegisterAgent)(nil),        // 2: capmesh.v1.RegisterAgent
	(*Heartbeat)(nil),            // 3: capmesh.v1.Heartbeat
	(*CaptureStatus)(nil),        // 4: capmesh.v1.CaptureStatus
	(*StartCapture)(nil),         // 5: capmesh.v1.StartCapture
	(*StopCapture)(nil),          // 6: capmesh.v1.StopCapture
	(*PacketBatch)(nil),          // 7: capmesh.v1.PacketBatch
	(*Packet)(nil),               // 8: capmesh.v1.Packet
	(*CreateSessionRequest)(nil), // 9: capmesh.v1.CreateSessionRequest
	(*StopSessionRequest)(nil),   // 10: capmesh.v1.StopSessionRequest
	(*GetSessionRequest)(nil),    // 11: capmesh.v1.GetSessionRequest
	(*StreamPacketsRequest)(nil), // 12: capmesh.v1.StreamPacketsRequest
	(*CaptureSession)(nil),       // 13: capmesh.v1.CaptureSession
	nil,                          // 14: capmesh.v1.RegisterAgent.InterfacesEntry
}
var file_api_capmesh_v1_capture_proto_depIdxs = []int32{
	2,  // 0: capmesh.v1.AgentMessage.register:type_name -> capmesh.v1.RegisterAgent
	3,  // 1: capmesh.v1.AgentMessage.heartbeat:type_name -> capmesh.v1.Heartbeat
	4,  // 2: capmesh.v1.AgentMessage.status:type_name -> capmesh.v1.CaptureStatus
	7,  // 3: capmesh.v1.AgentMessage.batch:type_name -> capmesh.v1.PacketBatch
	5,  // 4: capmesh.v1.AgentCommand.start:type_name -> capmesh.v1.StartCapture
	6,  // 5: capmesh.v1.AgentCommand.stop:type_name -> capmesh.v1.StopCapture
	14, // 6: capmesh.v1.RegisterAgent.interfaces:type_name -> capmesh.v1.RegisterAgent.InterfacesEntry
	8,  // 7: capmesh.v1.PacketBatch.packets:type_name -> capmesh.v1.Packet
	0,  // 8: capmesh.v1.AgentService.Connect:input_type -> capmesh.v1.AgentMessage
	9,  // 9: capmesh.v1.CaptureService.CreateSession:input_type -> capmesh.v1.CreateSessionRequest
	10, // 10: capmesh.v1.CaptureService.StopSession:input_type -> capmesh.v1.StopSessionRequest
	11, // 11: capmesh.v1.CaptureService.GetSession:input_type -> capmesh.v1.GetSessionRequest
	12, // 12: capmesh.v1.CaptureService.StreamPackets:input_type -> capmesh.v1.StreamPacketsRequest
	1,  // 13: capmesh.v1.AgentService.Connect:output_type -> capmesh.v1.AgentCommand
	13, // 14: capmesh.v1.CaptureService.CreateSession:output_type -> capmesh.v1.CaptureSession
	13, // 15: capmesh.v1.CaptureService.StopSession:output_type -> capmesh.v1.CaptureSession
	13, // 16: capmesh.v1.CaptureService.GetSession:output_type -> capmesh.v1.CaptureSession
	7,  // 17: capmesh.v1.CaptureService.StreamPackets:output_type -> capmesh.v1.PacketBatch
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_capmesh_v1_capture_proto_init() }
func file_api_capmesh_v1_capture_proto_init() {
	if File_api_capmesh_v1_capture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_capmesh_v1_capture_proto_rawDesc), len(file_api_capmesh_v1_capture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_capmesh_v1_capture_proto_goTypes,
		DependencyIndexes: file_api_capmesh_v1_capture_proto_depIdxs,
		MessageInfos:      file_api_capmesh_v1_capture_proto_msgTypes,
	}.Build()
	File_api_capmesh_v1_capture_proto = out.File
	file_api_capmesh_v1_capture_proto_goTypes = nil
	file_api_capmesh_v1_capture_proto_depIdxs = nil
}
