apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: capmesh
resources:
  - namespace.yaml
  - configmap.yaml
  - rbac.yaml
  - server-deployment.yaml
  - server-service.yaml
  - agent-daemonset.yaml
