apiVersion: v1
kind: Service
metadata:
  name: capmesh-server
spec:
  selector:
    app.kubernetes.io/name: capmesh-server
  ports:
    - name: grpc
      port: 18443
      targetPort: grpc
    - name: metrics
      port: 19090
      targetPort: metrics
