apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: capmesh-captures
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: capmesh-local
  volumeName: capmesh-captures-local
  resources:
    requests:
      storage: 100Gi
